wandb_version: 1

base_e:
  value: 128
batch_size:
  value: 256
dropout:
  value: 0
freq:
  value: 2
incr_e:
  value: 128
initializer:
  value: squeezenet
lr:
  value: 0.01
num_epochs:
  value: 10
pct_3x3:
  value: 0.4
sr:
  value: 0.75
weight_decay:
  value: 3.631910598605084e-05
