wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1717790050
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 16
      - 23
      - 24
      - 37
      4: 3.11.5
      5: 0.17.0
      8:
      - 2
      - 4
      - 5
      13: darwin-arm64
batch_size:
  desc: null
  value: 128
dropout:
  desc: null
  value: 0.1
fc_units:
  desc: null
  value: 64
kernels:
  desc: null
  value:
  - 32
  - 32
  - 16
  - 16
lr:
  desc: null
  value: 1.0741909911647447
num_epochs:
  desc: null
  value: 30
weight_decay:
  desc: null
  value: 1.0157190209867075
