wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.3
fc_units:
  value: 32
kernels:
  value:
  - 16
  - 16
  - 16
  - 16
lr:
  value: 1.00358253438629
num_epochs:
  value: 30
weight_decay:
  value: 1.0143396263942268
