wandb_version: 1

base_e:
  value: 128
batch_size:
  value: 256
dropout:
  value: 0.2
freq:
  value: 2
incr_e:
  value: 128
initializer:
  value: squeezenet
lr:
  value: 0.01
num_epochs:
  value: 15
pct_3x3:
  value: 0.3
sr:
  value: 0.125
weight_decay:
  value: 0.07849755595622707
