wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.1
fc_units:
  value: 32
kernels:
  value:
  - 32
  - 32
  - 16
  - 16
lr:
  value: 1.0637716458961524
num_epochs:
  value: 30
weight_decay:
  value: 1.0288880727807563
