wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0
fc_units:
  value: 32
kernels:
  value:
  - 32
  - 32
  - 16
  - 16
lr:
  value: 1.027053856086842
num_epochs:
  value: 30
weight_decay:
  value: 1.073914228196687
