wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.17.0
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1719865344
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      - 103
      2:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      - 103
      3:
      - 1
      - 7
      - 23
      - 66
      4: 3.11.5
      5: 0.17.0
      8:
      - 2
      - 4
      - 5
      13: darwin-arm64
    m:
    - 1: trainer/global_step
      6:
      - 3
